Repository Statutis/api, pull requests merged in 2022-04, with the labels that each got.

#49 Worker Service pour tâches cron
  .github/workflows/docker.yml
  Cron.DockerFile
  Statutis.Business/Service/ServiceService.cs
  Statutis.Core/Interfaces/Business/Service/IServiceService.cs
  Statutis.Core/Interfaces/DbRepository/Service/IServiceRepository.cs
  Statutis.Cron/Program.cs
  Statutis.Cron/Properties/launchSettings.json
  Statutis.Cron/ServiceChecker/DnsCheckerService.cs
  Statutis.Cron/ServiceChecker/HttpCheckerService.cs
  Statutis.Cron/ServiceChecker/PingCheckerWorker.cs
  Statutis.Cron/Statutis.Cron.csproj
  Statutis.Cron/appsettings.Development.json
  Statutis.Cron/appsettings.json
  Statutis.DbRepository/Repository/Service/ServiceRepository.cs
  Statutis.sln
Labels: Cron

#50 fix : problème de publication
  Statutis.API/appsettings.json
  Statutis.Cron/appsettings.Development.json
  Statutis.Cron/appsettings.json
Labels: Cron

#54 fix : récupération de l'état global
  Statutis.Business/History/HistoryEntryService.cs
Labels: API

#68 Feature/team
  Statutis.API/Controllers/AuthenticateController.cs
  Statutis.API/Controllers/TeamController.cs
  Statutis.API/Controllers/UserController.cs
  Statutis.API/Form/TeamForm.cs
  Statutis.API/Models/TeamModel.cs
  Statutis.API/Models/UserModel.cs
  Statutis.Business/AuthService.cs
  Statutis.Business/TeamService.cs
  Statutis.Core/Interfaces/Business/IAuthService.cs
  Statutis.Core/Interfaces/Business/ITeamService.cs
  Statutis.Core/Interfaces/DbRepository/ITeamRepository.cs
  Statutis.DbRepository/Repository/TeamRepository.cs
Labels: Buisness, Core, API, DbRepository

#78 feat: Add endPoint HttpService
  Statutis.API/Controllers/ServiceController.cs
  Statutis.API/Form/HttpForm.cs
  Statutis.API/Models/HttpServiceModel.cs
Labels: enhancement

#79 feat: add ping service end-point
  Statutis.API/Controllers/ServiceController.cs
  Statutis.API/Form/PingForm.cs
  Statutis.API/Models/PingServiceModel.cs
Labels: enhancement

#80 fix: service type name uri
  Statutis.API/Controllers/ServiceController.cs
Labels: bug

#83 Fix URI
  Statutis.API/Controllers/ServiceController.cs
Labels: bug

#84 Add endpoints to retrieve specific service
  Statutis.API/Controllers/ServiceController.cs
  Statutis.API/Models/ServiceModel.cs
  Statutis.Business/Service/ServiceService.cs
  Statutis.Core/Interfaces/Business/Service/IServiceService.cs
  Statutis.Core/Interfaces/DbRepository/Service/IServiceRepository.cs
  Statutis.DbRepository/Repository/Service/ServiceRepository.cs
Labels: documentation, enhancement
